version: '3.8'
volumes:
  data:
services:  
  mongodbcontainer:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:      
      - data:/data/db
      - ./tv-shows.json:/data/import/tv-shows.json
 


